// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('app', ['CoolForm', 'AnotherDemoModule']);

  angular.module('DemoModule', []).factory('demoFactory', function() {
    var validator;
    validator = function(name, fields, options) {
      if ((fields[name].value != null) && fields[name].value === 'demo') {
        return true;
      }
      return false;
    };
    return {
      validator: validator,
      init: null
    };
  });

  angular.module('AnotherDemoModule', []).directive('demoDirective', function() {
    var l;
    l = function(scope) {
      scope.value = scope.field.value;
      scope.field.onChange.push(function(v) {
        if (v !== scope.value) {
          return scope.value = v;
        }
      });
      return scope.$watch('value', function(v, o) {
        return scope.field.set(v);
      });
    };
    return {
      restrict: 'E',
      scope: {
        field: '=',
        service: '='
      },
      template: "<input type=\"text\" ng-model=\"value\"/>",
      link: l
    };
  });

}).call(this);
